-- AlterTable
ALTER TABLE "Vehicle" ADD COLUMN     "axleCount" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "hazmat" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "heightM" DOUBLE PRECISION NOT NULL DEFAULT 4.0,
ADD COLUMN     "lengthM" DOUBLE PRECISION NOT NULL DEFAULT 12.0,
ADD COLUMN     "weightTon" DOUBLE PRECISION NOT NULL DEFAULT 26,
ADD COLUMN     "widthM" DOUBLE PRECISION NOT NULL DEFAULT 2.55;
